### ISSUE TITLE
Unable to deploy spider

### ISSUE THREAD

**Issue by chandanch** [buckyroberts/Spider#24]
I'm getting the error as py command not found?

**Comment by saitan** [comment]
Traceback (most recent call last):
  File "/home/cyruh/hack/Spider-master/main.py", line 14, in <module>
    Spider(PROJECT_NAME, HOMEPAGE, DOMAIN_NAME)
  File "/home/cyruh/hack/Spider-master/spider.py", line 24, in __init__
    self.crawl_page('First spider', Spider.base_url)
  File "/home/cyruh/hack/Spider-master/spider.py", line 43, in crawl_page
    Spider.update_files()
  File "/home/cyruh/hack/Spider-master/spider.py", line 73, in update_files
    set_to_file(Spider.queue, Spider.queue_file)
  File "/home/cyruh/hack/Spider-master/general.py", line 49, in set_to_file
    with open(filename,"w") as f:
NameError: name 'filename' is not defined

**Comment by buckyroberts** [comment]
Fixed
