### ISSUE TITLE
Decode Error while writing to a file

### ISSUE THREAD

**Issue by litanlitudan** [buckyroberts/Spider#29]
Got this error
'utf-8' codec can't decode byte 0xb7 in position 10239: invalid start byte
when trying to write a file.

Did some search on google, but most people said using decode("utf-8", "ignore") or decode("utf-8", "replace").

Is there any other way to solve this problem?

Thanks

**Comment by num3ri** [comment]
I have the same problem, with any pages with encode "windows-1252" and many other local encode (latin,french etc..) The error reported was always "unicode text" with codes "0xa0" ... "0xe0", and so on, in any "random"  position. I tryed the solution described in :
[http://stackoverflow.com/questions/2365411/python-convert-unicode-to-ascii-without-errors]
but this solution sometimes do not works.

**Comment by dbchung** [comment]
same here:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\Python35-32\lib\threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "C:\Users\user\Desktop\python work\crawler.py", line 29, in work
    Spider.crawl_page(threading.current_thread().name, url)
  File "C:\Users\user\Desktop\python work\spider.py", line 43, in crawl_page
    Spider.update_files()
  File "C:\Users\user\Desktop\python work\spider.py", line 73, in update_files
    set_to_file(Spider.queue, Spider.queue_file)
  File "C:\Users\user\Desktop\python work\general.py", line 51, in set_to_file
    f.write(l+"\n")
UnicodeEncodeError: 'cp950' codec can't encode character '\u5803' in position 22: illegal multibyte sequence

**Comment by ghost** [comment]
The project has been moved to https://github.com/AbdulSheikh/Spider . This project is no longer supported In this github account.
